// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/shorturl/v1/shorturl.proto

package v1

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for adding a single URL
type AddShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShortenRequest) Reset() {
	*x = AddShortenRequest{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShortenRequest) ProtoMessage() {}

func (x *AddShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShortenRequest.ProtoReflect.Descriptor instead.
func (*AddShortenRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *AddShortenRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Response for adding a single URL
type AddShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShortenResponse) Reset() {
	*x = AddShortenResponse{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShortenResponse) ProtoMessage() {}

func (x *AddShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShortenResponse.ProtoReflect.Descriptor instead.
func (*AddShortenResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *AddShortenResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// Request for getting URL by short name
type GetURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortName     string                 `protobuf:"bytes,1,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{2}
}

func (x *GetURLRequest) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

// Response for getting URL by short name
type GetURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	IsRemoved     bool                   `protobuf:"varint,2,opt,name=is_removed,json=isRemoved,proto3" json:"is_removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLResponse) Reset() {
	*x = GetURLResponse{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResponse) ProtoMessage() {}

func (x *GetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResponse.ProtoReflect.Descriptor instead.
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{3}
}

func (x *GetURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetURLResponse) GetIsRemoved() bool {
	if x != nil {
		return x.IsRemoved
	}
	return false
}

// Single element for batch request
type BatchRequestElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequestElement) Reset() {
	*x = BatchRequestElement{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequestElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequestElement) ProtoMessage() {}

func (x *BatchRequestElement) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequestElement.ProtoReflect.Descriptor instead.
func (*BatchRequestElement) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{4}
}

func (x *BatchRequestElement) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchRequestElement) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// Request for batch URL addition
type AddShortenBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*BatchRequestElement `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShortenBatchRequest) Reset() {
	*x = AddShortenBatchRequest{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShortenBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShortenBatchRequest) ProtoMessage() {}

func (x *AddShortenBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShortenBatchRequest.ProtoReflect.Descriptor instead.
func (*AddShortenBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{5}
}

func (x *AddShortenBatchRequest) GetUrls() []*BatchRequestElement {
	if x != nil {
		return x.Urls
	}
	return nil
}

// Single element for batch response
type BatchResponseElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponseElement) Reset() {
	*x = BatchResponseElement{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponseElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponseElement) ProtoMessage() {}

func (x *BatchResponseElement) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponseElement.ProtoReflect.Descriptor instead.
func (*BatchResponseElement) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{6}
}

func (x *BatchResponseElement) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchResponseElement) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// Response for batch URL addition
type AddShortenBatchResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Urls          []*BatchResponseElement `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShortenBatchResponse) Reset() {
	*x = AddShortenBatchResponse{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShortenBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShortenBatchResponse) ProtoMessage() {}

func (x *AddShortenBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShortenBatchResponse.ProtoReflect.Descriptor instead.
func (*AddShortenBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{7}
}

func (x *AddShortenBatchResponse) GetUrls() []*BatchResponseElement {
	if x != nil {
		return x.Urls
	}
	return nil
}

// Request for getting user URLs
type GetUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsRequest) Reset() {
	*x = GetUserURLsRequest{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsRequest) ProtoMessage() {}

func (x *GetUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsRequest.ProtoReflect.Descriptor instead.
func (*GetUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{8}
}

// Response for getting user URLs (streaming)
type GetUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsResponse) Reset() {
	*x = GetUserURLsResponse{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsResponse) ProtoMessage() {}

func (x *GetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserURLsResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *GetUserURLsResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// Request for removing URLs
type RemoveURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortNames    []string               `protobuf:"bytes,1,rep,name=short_names,json=shortNames,proto3" json:"short_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveURLsRequest) Reset() {
	*x = RemoveURLsRequest{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveURLsRequest) ProtoMessage() {}

func (x *RemoveURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveURLsRequest.ProtoReflect.Descriptor instead.
func (*RemoveURLsRequest) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveURLsRequest) GetShortNames() []string {
	if x != nil {
		return x.ShortNames
	}
	return nil
}

// Response for ping
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{11}
}

func (x *PingResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// Response for statistics
type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shorturl_v1_shorturl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{12}
}

func (x *GetStatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetStatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_api_shorturl_v1_shorturl_proto protoreflect.FileDescriptor

const file_api_shorturl_v1_shorturl_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/shorturl/v1/shorturl.proto\x12\vshorturl.v1\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\x11AddShortenRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"1\n" +
	"\x12AddShortenResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\".\n" +
	"\rGetURLRequest\x12\x1d\n" +
	"\n" +
	"short_name\x18\x01 \x01(\tR\tshortName\"A\n" +
	"\x0eGetURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"is_removed\x18\x02 \x01(\bR\tisRemoved\"_\n" +
	"\x13BatchRequestElement\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"N\n" +
	"\x16AddShortenBatchRequest\x124\n" +
	"\x04urls\x18\x01 \x03(\v2 .shorturl.v1.BatchRequestElementR\x04urls\"Z\n" +
	"\x14BatchResponseElement\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"P\n" +
	"\x17AddShortenBatchResponse\x125\n" +
	"\x04urls\x18\x01 \x03(\v2!.shorturl.v1.BatchResponseElementR\x04urls\"\x14\n" +
	"\x12GetUserURLsRequest\"U\n" +
	"\x13GetUserURLsResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"4\n" +
	"\x11RemoveURLsRequest\x12\x1f\n" +
	"\vshort_names\x18\x01 \x03(\tR\n" +
	"shortNames\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"<\n" +
	"\x10GetStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users2\x99\x04\n" +
	"\x0fShortURLService\x12M\n" +
	"\n" +
	"AddShorten\x12\x1e.shorturl.v1.AddShortenRequest\x1a\x1f.shorturl.v1.AddShortenResponse\x12A\n" +
	"\x06GetURL\x12\x1a.shorturl.v1.GetURLRequest\x1a\x1b.shorturl.v1.GetURLResponse\x12\\\n" +
	"\x0fAddShortenBatch\x12#.shorturl.v1.AddShortenBatchRequest\x1a$.shorturl.v1.AddShortenBatchResponse\x12R\n" +
	"\vGetUserURLs\x12\x1f.shorturl.v1.GetUserURLsRequest\x1a .shorturl.v1.GetUserURLsResponse0\x01\x12D\n" +
	"\n" +
	"RemoveURLs\x12\x1e.shorturl.v1.RemoveURLsRequest\x1a\x16.google.protobuf.Empty\x129\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x19.shorturl.v1.PingResponse\x12A\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x1d.shorturl.v1.GetStatsResponseB,Z*github.com/Alheor/shorturl/pkg/shorturl/v1b\x06proto3"

var (
	file_api_shorturl_v1_shorturl_proto_rawDescOnce sync.Once
	file_api_shorturl_v1_shorturl_proto_rawDescData []byte
)

func file_api_shorturl_v1_shorturl_proto_rawDescGZIP() []byte {
	file_api_shorturl_v1_shorturl_proto_rawDescOnce.Do(func() {
		file_api_shorturl_v1_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_shorturl_v1_shorturl_proto_rawDesc), len(file_api_shorturl_v1_shorturl_proto_rawDesc)))
	})
	return file_api_shorturl_v1_shorturl_proto_rawDescData
}

var file_api_shorturl_v1_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_shorturl_v1_shorturl_proto_goTypes = []any{
	(*AddShortenRequest)(nil),       // 0: shorturl.v1.AddShortenRequest
	(*AddShortenResponse)(nil),      // 1: shorturl.v1.AddShortenResponse
	(*GetURLRequest)(nil),           // 2: shorturl.v1.GetURLRequest
	(*GetURLResponse)(nil),          // 3: shorturl.v1.GetURLResponse
	(*BatchRequestElement)(nil),     // 4: shorturl.v1.BatchRequestElement
	(*AddShortenBatchRequest)(nil),  // 5: shorturl.v1.AddShortenBatchRequest
	(*BatchResponseElement)(nil),    // 6: shorturl.v1.BatchResponseElement
	(*AddShortenBatchResponse)(nil), // 7: shorturl.v1.AddShortenBatchResponse
	(*GetUserURLsRequest)(nil),      // 8: shorturl.v1.GetUserURLsRequest
	(*GetUserURLsResponse)(nil),     // 9: shorturl.v1.GetUserURLsResponse
	(*RemoveURLsRequest)(nil),       // 10: shorturl.v1.RemoveURLsRequest
	(*PingResponse)(nil),            // 11: shorturl.v1.PingResponse
	(*GetStatsResponse)(nil),        // 12: shorturl.v1.GetStatsResponse
	(*empty.Empty)(nil),             // 13: google.protobuf.Empty
}
var file_api_shorturl_v1_shorturl_proto_depIdxs = []int32{
	4,  // 0: shorturl.v1.AddShortenBatchRequest.urls:type_name -> shorturl.v1.BatchRequestElement
	6,  // 1: shorturl.v1.AddShortenBatchResponse.urls:type_name -> shorturl.v1.BatchResponseElement
	0,  // 2: shorturl.v1.ShortURLService.AddShorten:input_type -> shorturl.v1.AddShortenRequest
	2,  // 3: shorturl.v1.ShortURLService.GetURL:input_type -> shorturl.v1.GetURLRequest
	5,  // 4: shorturl.v1.ShortURLService.AddShortenBatch:input_type -> shorturl.v1.AddShortenBatchRequest
	8,  // 5: shorturl.v1.ShortURLService.GetUserURLs:input_type -> shorturl.v1.GetUserURLsRequest
	10, // 6: shorturl.v1.ShortURLService.RemoveURLs:input_type -> shorturl.v1.RemoveURLsRequest
	13, // 7: shorturl.v1.ShortURLService.Ping:input_type -> google.protobuf.Empty
	13, // 8: shorturl.v1.ShortURLService.GetStats:input_type -> google.protobuf.Empty
	1,  // 9: shorturl.v1.ShortURLService.AddShorten:output_type -> shorturl.v1.AddShortenResponse
	3,  // 10: shorturl.v1.ShortURLService.GetURL:output_type -> shorturl.v1.GetURLResponse
	7,  // 11: shorturl.v1.ShortURLService.AddShortenBatch:output_type -> shorturl.v1.AddShortenBatchResponse
	9,  // 12: shorturl.v1.ShortURLService.GetUserURLs:output_type -> shorturl.v1.GetUserURLsResponse
	13, // 13: shorturl.v1.ShortURLService.RemoveURLs:output_type -> google.protobuf.Empty
	11, // 14: shorturl.v1.ShortURLService.Ping:output_type -> shorturl.v1.PingResponse
	12, // 15: shorturl.v1.ShortURLService.GetStats:output_type -> shorturl.v1.GetStatsResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_shorturl_v1_shorturl_proto_init() }
func file_api_shorturl_v1_shorturl_proto_init() {
	if File_api_shorturl_v1_shorturl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_shorturl_v1_shorturl_proto_rawDesc), len(file_api_shorturl_v1_shorturl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shorturl_v1_shorturl_proto_goTypes,
		DependencyIndexes: file_api_shorturl_v1_shorturl_proto_depIdxs,
		MessageInfos:      file_api_shorturl_v1_shorturl_proto_msgTypes,
	}.Build()
	File_api_shorturl_v1_shorturl_proto = out.File
	file_api_shorturl_v1_shorturl_proto_goTypes = nil
	file_api_shorturl_v1_shorturl_proto_depIdxs = nil
}
